### ISSUE TITLE
Overview length notice

### ISSUE THREAD

**Issue by erinwagner** [EcoSIS/ecosml-webapp#25]
**Describe the bug**
On dev.ecosml.org. When I hit the +CREATE button, I get a pop up that says "Please provide a longer overview."  This is confusing since the instructions say to keep the overview to one sentence.  I tried to include more information and even started typing random things to add length, but I still get the message.

**To Reproduce**
1. Go to 'https://dev.ecosml.org/create'
2. Fill out required fields
3. Click on '+CREATE'

**Expected behavior**
I expected a package to be created, or that a slightly longer overview would be acceptable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac Mojave 10.14.2
 - Browser: Chrome
 - Version 71.0.3578.98

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jrmerz** [comment]
@erinwagner fix deployed to dev.  Can you give it a test?

**Comment by jrmerz** [comment]
Deployed to production
