### ISSUE TITLE
unknown package when creating release

### ISSUE THREAD

**Issue by erinwagner** [EcoSIS/ecosml-webapp#29]
**Describe the bug**
After filling in all of the fields on previous tabs - Error when creating a package: Error creating release: Unknown package: undefined

**To Reproduce**
1. Go to 'Releases'
2. Click on 'Create Release'

**Expected behavior**
Release should be created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mojave 10.14.3
 - Browser: Chrome
 - Version: 73.0.3683.86

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jrmerz** [comment]
@erinwagner Should be fixed, give it a try

**Comment by jrmerz** [comment]
please reopen if still having an issue.
