### ISSUE TITLE
Can't create package

### ISSUE THREAD

**Issue by erinwagner** [EcoSIS/ecosml-webapp#30]
**Describe the bug**
Get error: Failed to create package: Invalid status code
Occurs when I try to create a  new package under the 'Basic Information' tab.

**To Reproduce**
1. Go to drop down menu
2. Click on 'Create Package'
3. Select 'EcoSML Managed Repository
4. Click on 'Next'
5. Fill in info
6. Select 'Stand Alone Package'
7. Click on 'Create'

**Expected behavior**
Expected 'Files' and 'Releases' tabs to appear to continue the creation process.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.3
 - Browser: Chrome 
 - Version: 73.0.3683.86

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jrmerz** [comment]
@erinwagner Should be fixed, give it a try

**Comment by jrmerz** [comment]
Closing, please reopen if you have this issue again
