### ISSUE TITLE
Readme won't render on ecosml site

### ISSUE THREAD

**Issue by adamchlus** [EcoSIS/ecosml-webapp#32]
I uploaded a Readme markdown file, it won't render on the ecosml site:

[https://ecosml.org/package/ca0e52d7-51c6-46da-b71b-99f3a868854a](https://ecosml.org/package/ca0e52d7-51c6-46da-b71b-99f3a868854a)

but it **DOES** render on the github page:

[https://github.com/EcoSML/3-Dimensional-LMA-leaf-level](https://github.com/EcoSML/3-Dimensional-LMA-leaf-level)

**Comment by serbinsh** [comment]
Same here:
https://ecosml.org/package/321fd209-079e-4d04-a50f-d54d61fcb5ca

**Comment by jrmerz** [comment]
patch fix here 3c6f277613d007291df251102970d61a0e021b90

**Comment by jrmerz** [comment]
This should be fixed now.  I'm not in love with the patch, so please reopen if you run into more issues with the markdown render.
