### ISSUE TITLE
"Create Package" message download link not working

### ISSUE THREAD

**Issue by walther3** [EcoSIS/ecosml-webapp#49]
**Describe the bug**
When trying to download package files immediately after creating a package it send you to a new tab, with a messaged saying "Not found".
**To Reproduce**
1. Create a package on dev.ecosml.org, with an EcoSML managed repository, code type: Stand alone application 
2. When "Package Created" message pops up, click on "Download package files" and it should take you to the error window. 

**Expected behavior**
I thought that when I clicked on "Download package files" that it would download. I can only download package files from the files tab after clicking out of the "Package Created" message. 

**Screenshots**
<img width="635" alt="Screen Shot 2020-05-05 at 7 28 29 PM" src="https://user-images.githubusercontent.com/55326013/81130107-2ae12880-8f0c-11ea-9306-32de5b410e8c.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser Firefox
 - Version 75.0 (64-bit)

**Comment by jrmerz** [comment]
@walther3 this issue and issues #50 and #51 have been pushed to dev.  Please test and if everything looks good, feel free to close.
