### ISSUE TITLE
GitHub repository release issue

### ISSUE THREAD

**Issue by walther3** [EcoSIS/ecosml-webapp#50]
**Describe the bug**
When clicking the "+CREATE" button under the "Releases" tab, a new window pops up with an error message "Cannot GET / new"

**To Reproduce**
1. Create package with a GitHub registered repository 
2. Click on "+CREATE" button under "Releases" tab

**Expected behavior**
I thought that it would show the Major, Minor, and Patch boxes as it did when hosted under the EcoSML repository.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 
 - Browser Firefox
 - Version 75.0 (64-bit)

**Comment by jrmerz** [comment]
fixed in d428b76

**Comment by walther3** [comment]
Problem is no longer visible on website
