### ISSUE TITLE
Admin DOI Page Misdirection

### ISSUE THREAD

**Issue by walther3** [EcoSIS/ecosml-webapp#52]
**Describe the bug**
When under "Admin DOI" page if you click on a package name to take you to the package, it will take you to a blank package page. 

**To Reproduce**
1. Go to 'Admin DOI'
2. Click on any package that has a DOI approved or one that is pending. 

**Expected behavior**
I was expecting the page to open for that package that shows when you look at the package in search. 

**Screenshots**
<img width="1636" alt="Screen Shot 2020-05-12 at 3 01 38 PM" src="https://user-images.githubusercontent.com/55326013/81739771-8443dd00-9461-11ea-8219-b6d51f0899b9.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Firefox 
 - Version: 76.0.1

**Comment by jrmerz** [comment]
@walther3 fix pushed to dev
