### ISSUE TITLE
Syncing of Respository

### ISSUE THREAD

**Issue by walther3** [EcoSIS/ecosml-webapp#53]
**Describe the bug**
When hosting the repository in github and trying to sync the repository an error shows up, with a 400 code in the web counsel. 

**To Reproduce**
1. Create a package under a github hosted repository.
2. After creating a release go back to "Basic Information" page and try to sync repository.
3. see error

**Expected behavior**
I was expecting the repository to sync so that the releases would show and I could then request a DOI. 

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Firefox
 - Version: 76.0.1

**Comment by jrmerz** [comment]
@walther3 fix pushed to dev
