### ISSUE TITLE
Be able to "deny" DOI requests

### ISSUE THREAD

**Issue by walther3** [EcoSIS/ecosml-webapp#54]
**Is your feature request related to a problem? Please describe.**
I noticed under DOI Admin that the only actions you can take are either requesting a revision or approving the DOI. I know in EcoSIS you cannot make certain changes to the files once a DOI is requested and it actually needs to be denied and then re-requested once the changes have been made. I am not sure if that applies here, but I think it might be good to actually be able to just deny someone's request. 

**Describe the solution you'd like**
I think there should be a "deny" option in the action drop down menu when approving DOIs

**Comment by jrmerz** [comment]
The admins will never reject a DOI, only ask for revisions.  Users can cancel the request if they wish.
