### ISSUE TITLE
Finish theme widget

### ISSUE THREAD

**Issue by jrmerz** [EcoSIS/ecosml-webapp#7]
We need to:

- Get complete list of terms
- User process works verify

**Comment by erinwagner** [comment]
I added some more themes and key words to the "facet themes" spreadsheet that Phil shared.  Themes: pathogen, damage, production.

**Comment by jrmerz** [comment]
Are we going to let users choose multiple values for theme?  Or just one theme/family/specific per model?

**Comment by erinwagner** [comment]
Are these themes that someone uses to describe a model they are uploading?  If so, then I would think only one theme would be able to apply to a model at a time.  As far as I know, a model is only made for one trait, disease, or quantity.  I can check to be sure, though.

**Comment by jrmerz** [comment]
Decision was to allow multiple themes.  Will implement.

**Comment by erinwagner** [comment]
Great!


Erin

________________________________
