### ISSUE TITLE
Error while Downloading Package and Sync Changes in File menu in Dev Instance for Managed Repository option

### ISSUE THREAD

**Issue by amrutavidwans** [EcoSIS/ecosml-webapp#82]
**Describe the bug**
Clicking on 'Download Package Files' returns '404:Not Found'. Choose Folder under Sync Changes results in 'Upload Error'.

**To Reproduce**
Steps to reproduce the 404:Not Found:
1. Go to 'Create'->Select 'EcoSML Managed Repository' -> Fill out the Basic Information -> Scroll down to 'Code Type' select Standalone Application -> Click 'Create' 
2. Go to 'My Packages' -> Select your package -> Click on 'Files'
3. Click on 'Download Package Files' -> See 404 error

Steps to reproduce the 'Upload Error':
1. Go to ecosml-dev github page -> Download your repo -> Add a file
2. Go to dev.ecosml.org -> Click on your username ->  Go to 'My Packages' -> Select your package -> Click on 'Files'
3. Click on 'Choose Folder' under 'Sync Changes' -> Select the repo folder -> Click 'Save Changes'
4. See 'Upload Error: {"error":true}'

**Expected behavior**
1. Download Package Files should result in downloading of the github repo files
2. Choosing Folder and Upload should result in commiting new files to github

**Screenshots**
![image](https://user-images.githubusercontent.com/12546910/121386318-8354d780-c90f-11eb-8183-0b48c94a7688.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.3
 - Browser: Firefox 88.0

**Comment by jrmerz** [comment]
These issues have to do with EcoSML not supporting default branch names changes.  Working through this now.

**Comment by jrmerz** [comment]
@amrutavidwans I have push the first fix for this to dev.  Can you test when you have a chance?

**Comment by amrutavidwans** [comment]
Yes, both Downloading of package and Sync Changes is working now.

**Comment by jrmerz** [comment]
great, let's chat at tomorrows meeting about rolling to production.  I'd like to have a coordinated test there as well.

**Comment by jrmerz** [comment]
@amrutavidwans this has been deployed to production, when you are back from vacation, can you verify everything looks fixed?

**Comment by amrutavidwans** [comment]
@jrmerz All the steps worked. Except, I get an error message while creating a release, although the release does get created.

![image](https://user-images.githubusercontent.com/12546910/124160817-45f0ef00-da62-11eb-9c0f-4f3aa3f94da0.png)

**Comment by jrmerz** [comment]
Humm, I have tried several times to recreate bug and have been unable.  Can you try again on your end and provide exact steps you preformed to create bug?

**Comment by amrutavidwans** [comment]
I was not able to re-create the bug either. Not sure why it happened that first time.

**Comment by jrmerz** [comment]
Ok, I'm going to close for now, but please reopen if you see again
